#
# 스프링 부트 애플리케이션 로컬 개발 환경 설정
#

spring:
  config:
    activate:
      on-profile:
        - dev
  # 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/gople?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: suihin
    password: tq3519
    driver-class-name: org.mariadb.jdbc.Driver

# 마이바티스 설정
mybatis:
  # 서버 구동시 마이바티스 동작 제어를 위한 설정
  configuration:
    # 매퍼 네임스페이스 단위로 동작되는 캐시 비활성화
    cache-enabled: false
    # SQL 세션 객체마다 가지고 있는 로컬 캐시의 적용 범위 설정
    local-cache-scope: STATEMENT
    # 지연 로딩 비활성화
    lazy-loading-enabled: false
    # 스네이크 케이스 표기법의 컬럼명을 카멜케이스 표기법으로 변환
    map-underscore-to-camel-case: true
    # 조회되는 값이 널 값일 경우, 누락되는 문제를 방지하기 위해 setter() 또는 Map의 put() 호출
    call-setters-on-nulls: true
    # 마이바티스에서 값이 널 값인 파라미터 처리
    jdbc-type-for-null: NULL
  # 매핑을 위한 클래스의 이름을 작성시, 해당 클래스가 속한 패키지 명 생략
  type-aliases-package: com.bins.gople.domain.**.dto
  # 마이바티스의 사용자 정의 타입 핸들러가 위치한 패키지를 지정하여, 값의 변환 수행시 해당 타입 핸들러가 적용되도록 설정
  type-handlers-package: com.bins.gople.global.common.mybatis
  # 매퍼 XML 파일의 경로 설정
  mapper-locations:
    - classpath:mappers/*_mapper.xml

# 로깅 설정
logging:
  level:
    root: info












